# Generated by Django 3.1.3 on 2023-04-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230406_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pass_mark',
            field=models.IntegerField(default=50),
        ),
    ]
