# Generated by Django 3.1.3 on 2023-04-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_course_pass_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pass_mark',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pass_mark',
            field=models.IntegerField(default=50),
        ),
    ]
